# Generated by Django 2.2.7 on 2019-12-28 17:48

from django.db import migrations, models
import genie.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('birth_year', models.IntegerField(max_length=4)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default=genie.models.Gender('male'), max_length=10)),
                ('won_oscar', models.BooleanField(default=False)),
                ('action_star', models.BooleanField(default=False)),
                ('comedy_star', models.BooleanField(default=False)),
            ],
        ),
    ]
