# Generated by Django 2.2.7 on 2020-01-11 19:40

from django.db import migrations, models
import genie.models


class Migration(migrations.Migration):

    dependencies = [
        ('genie', '0002_auto_20191228_1748'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actor',
            old_name='comedy_star',
            new_name='comedian',
        ),
        migrations.AddField(
            model_name='actor',
            name='hair_color',
            field=models.CharField(choices=[('blond', 'Blond'), ('black', 'Black'), ('brown', 'Brown'), ('red', 'Red')], default=genie.models.HairColor('blond'), max_length=10),
        ),
        migrations.AddField(
            model_name='actor',
            name='skin_color',
            field=models.CharField(choices=[('white', 'White'), ('black', 'Black'), ('yellow', 'Yellow'), ('brown', 'Brown')], default=genie.models.Ethnicity('white'), max_length=10),
        ),
    ]
