# Generated by Django 2.2.7 on 2020-01-12 14:23

from django.db import migrations, models
import genie.libs.enums


class Migration(migrations.Migration):

    dependencies = [
        ('genie', '0003_auto_20200111_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='country',
            field=models.CharField(choices=[('USA', 'USA'), ('England', 'England'), ('China', 'China'), ('Canada', 'Canada'), ('other country', 'Other')], default=genie.libs.enums.Country('USA'), max_length=10),
        ),
    ]
