# Generated by Django 2.2.7 on 2020-01-13 17:04

from django.db import migrations, models
import genie.libs.enums


class Migration(migrations.Migration):

    dependencies = [
        ('genie', '0004_actor_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='country',
            field=models.CharField(choices=[('USA', 'USA'), ('England', 'England'), ('China', 'China'), ('Canada', 'Canada'), ('other country', 'Other')], default=genie.libs.enums.Country('USA'), max_length=100),
        ),
        migrations.AlterField(
            model_name='actor',
            name='hair_color',
            field=models.CharField(choices=[('blond', 'Blond'), ('black', 'Black'), ('brown', 'Brown'), ('red', 'Red')], default=genie.libs.enums.HairColor('blond'), max_length=100),
        ),
        migrations.AlterField(
            model_name='actor',
            name='skin_color',
            field=models.CharField(choices=[('white', 'White'), ('black', 'Black'), ('yellow', 'Yellow'), ('brown', 'Brown')], default=genie.libs.enums.Ethnicity('white'), max_length=100),
        ),
    ]
